-- PHOENIX SUMMER CUP 2026 — LẦN 2
-- Chạy toàn bộ file này trong Supabase > SQL Editor > New query > Run

create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  game_name text not null,
  uid text not null,
  facebook_url text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists players_game_name_unique on public.players (lower(game_name));
create unique index if not exists players_uid_unique on public.players (uid);
create unique index if not exists players_facebook_unique on public.players (lower(facebook_url));

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  team_number integer not null,
  position integer not null,
  player_id uuid references public.players(id) on delete cascade,
  game_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.players enable row level security;
alter table public.teams enable row level security;
alter table public.admins enable row level security;

grant select, insert on public.players to anon;
grant select on public.teams to anon;
grant select, insert, update, delete on public.players to authenticated;
grant select, insert, update, delete on public.teams to authenticated;
grant select on public.admins to authenticated;

drop policy if exists "public read player names" on public.players;
create policy "public read player names"
on public.players for select to anon
using (true);

drop policy if exists "public register player" on public.players;
create policy "public register player"
on public.players for insert to anon
with check (
  char_length(game_name) between 2 and 40
  and uid ~ '^[0-9]{5,20}$'
  and char_length(facebook_url) between 10 and 300
  and (select count(*) from public.players) < 55
);

drop policy if exists "public read teams" on public.teams;
create policy "public read teams"
on public.teams for select to anon
using (true);

drop policy if exists "admin checks self" on public.admins;
create policy "admin checks self"
on public.admins for select to authenticated
using (user_id = auth.uid());

drop policy if exists "admins manage players" on public.players;
create policy "admins manage players"
on public.players for all to authenticated
using (exists(select 1 from public.admins a where a.user_id = auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins manage teams" on public.teams;
create policy "admins manage teams"
on public.teams for all to authenticated
using (exists(select 1 from public.admins a where a.user_id = auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id = auth.uid()));

-- SAU KHI tạo tài khoản Admin trong Authentication > Users,
-- thay UUID dưới đây bằng User UID rồi chạy riêng dòng INSERT:
-- insert into public.admins(user_id) values ('DÁN-USER-UID-VÀO-ĐÂY');
